name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean install
        working-directory: ${{ github.workspace }}/back
      - name: search jacoco report
        run: ls ${{ github.workspace }}/back/target/site/jacoco
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: backend-test-result
          path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
