name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean install
        working-directory: ${{ github.workspace }}/back

      - name: Upload backend test results as artifact
        uses: actions/upload-artifact@v4 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: backend-test-result
          path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml

  frontend:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build and test project
        run: |
          npm ci
          npm run build --if-present
          npm run test:prod
        working-directory: ${{ github.workspace }}/front

      - name: Upload frontend test results as artifact
      - uses: actions/upload-artifact@v4 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: frontend-test-result
          path: ${{ github.workspace }}/front/coverage/bobapp/index.html
